/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type CreateImportJob struct {

	// Data Source
	DataSource string `json:"dataSource"`

	// Index 명
	Index string `json:"index"`

	// 버킷 이름
	BucketName string `json:"bucketName"`

	// Import 할 파일 경로
	ObjectKey string `json:"objectKey"`

	// Bulk 포맷 여부
	IsBulkFormat bool `json:"isBulkFormat"`
}
