/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type CreateCluster struct {

	// 클러스터 이름
	ClusterName string `json:"clusterName"`

	// 사용할 Elasticsearch
	ElasticSearchVersionCode string `json:"elasticSearchVersionCode"`

	// Kibana의 http port
	KibanaHttpPort string `json:"kibanaHttpPort"`

	// Kibana 접속 ID
	KibanaUserName string `json:"kibanaUserName"`

	// Kibana 접속 Password
	KibanaUserPassword string `json:"kibanaUserPassword"`

	// 사용할 OS 타입
	SoftwareProductCode string `json:"softwareProductCode"`

	// 사용할 VPC No
	VpcNo int32 `json:"vpcNo"`

	// 매니저 노드의 HW 스펙
	ManagerNodeProductCode string `json:"managerNodeProductCode"`

	// 매니저 노드가 위치할 Subnet No
	ManagerNodeSubnetNo int32 `json:"managerNodeSubnetNo"`

	// 데이터 노드의 HW 스펙
	DataNodeProductCode string `json:"dataNodeProductCode"`

	// 데이터 노드의 개수
	DataNodeCount int32 `json:"dataNodeCount"`

	// 데이터 노드가 위치할 Subnet No
	DataNodeSubnetNo int32 `json:"dataNodeSubnetNo"`

	// 데이터 노드의 스토리지 용량
	DataNodeStorageSize int32 `json:"dataNodeStorageSize"`

	// 매니저 노드 SSH 접속 시 사용될 인증키 이름
	LoginKeyName string `json:"loginKeyName"`

	// 매니저 노드 이중화 여부
	IsDualManager bool `json:"isDualManager"`

	// 마스터 전용 노드 활성화 여부
	IsMasterOnlyNodeActivated bool `json:"isMasterOnlyNodeActivated"`

	// 마스터 노드가 위치할 Subnet No
	MasterNodeSubnetNo int32 `json:"masterNodeSubnetNo,omitempty"`

	// 마스터 노드의 HW 스펙
	MasterNodeProductCode string `json:"masterNodeProductCode,omitempty"`

	// 마스터 노드의 개수
	MasterNodeCount int32 `json:"masterNodeCount,omitempty"`
}
