/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type CreateSnapshot struct {

	// Snapshot의 이름
	SnapshotName string `json:"snapshotName"`

	// Snapshot을 저장할 bucket 이름
	BucketName string `json:"bucketName"`
}
