/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type NodeProduct struct {

	// 사용할 OS 타입
	SoftwareProductCode string `json:"softwareProductCode"`

	// 노드가 위치할 Subnet No
	SubnetNo int32 `json:"subnetNo"`
}
