/*
 * api
 *
 * Search Engine Service(VPC) Open API<br/>https://vpcsearchengine.apigw.ntruss.com/api/v1
 *
 * API version: 2022-04-21T09:07:51Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vses

type SetSnapshotScheduling struct {

	// Snapshot을 저장할 bucket 이름
	BucketName string `json:"bucketName"`

	// Snapshot 이름
	SnapshotName string `json:"snapshotName"`

	// Scheduling을 실행할 일
	ScheduledDay string `json:"scheduledDay"`

	// Scheduling을 실행할 시간
	ScheduledHour int32 `json:"scheduledHour"`

	// Scheduling을 실행할 분
	ScheduledMinute int32 `json:"scheduledMinute"`
}
