/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type AddNodesInCluster struct {

	// 추가할 브로커 노드의 개수
	NewBrokerNodeCount int32 `json:"newBrokerNodeCount"`
}
