/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type EnableBrokerNodePublicEndpoint struct {

	// 로드밸런서 인스턴스 번호
	LoadBalancerInstanceNo int32 `json:"loadBalancerInstanceNo"`
}
