/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type GetSubnetList struct {

	// 사용할 VPC No
	VpcNo               int32  `json:"vpcNo"`

	// 사용할 할 OS 타입
	SoftwareProductCode string `json:"softwareProductCode"`
}
