/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type NodeProduct struct {

	// 사용할 할 OS 타입
	SoftwareProductCode string `json:"softwareProductCode"`

	// 노드가 위치할 Subnet No
	SubnetNo            int32  `json:"subnetNo"`
}
