/*
 * api
 *
 * Cloud Data Streaming Service Open API<br/>https://clouddatastreamingservice.apigw.ntruss.com/api/v1
 *
 * API version: 2021-12-21T11:54:01Z
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package vcdss

type RestartKafkaServicePerNode struct {

	// Kafka 서비스를 재시작할 서버의 인스턴스 번호
	ComputeInstanceNoList []int32 `json:"computeInstanceNoList"`
}
